export declare const QUERY_ACCOUNT_BALANCE: string;
export declare const QUERY_ACCOUNT_FEED: string;
export declare const QUERY_ACCOUNT_FEED_PAGINATED: string;
export declare const QUERY_ACCOUNT_ID: string;
export declare const QUERY_ACCOUNT_INVESTMENTS: string;
export declare const QUERY_GET_PIX_KEYS: string;
export declare const MUTATION_CREATE_BOLETO: string;
export declare const MUTATION_CREATE_MONEY_REQUEST: string;
export declare const MUTATION_CREATE_PIX_MONEY_REQUEST: string;
